[env:waveshare-esp32s3-epaper154]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; --- Board has an ESP32-S3-PICO-1-N8R8: 8 MB flash ---
board_upload.flash_size = 8MB
board_build.partitions = default.csv

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

monitor_speed = 115200
upload_speed = 921600
; If auto-detection of the COM/serial port ever picks the wrong one,
; uncomment and set this manually, e.g.:
; upload_port = COM5
; monitor_port = COM5

lib_deps =
    zinggjm/GxEPD2 @ ^1.6.9
    adafruit/Adafruit GFX Library @ ^1.12.6
    adafruit/Adafruit BusIO @ ^1.17.4
    adafruit/Adafruit Unified Sensor @ ^1.1.15
    adafruit/Adafruit SHTC3 Library @ ^1.0.2
    https://github.com/SolderedElectronics/Soldered-PCF85063A-RTC-Module-Arduino-Library.git